version: '3'
services:
  bla:
    image: jmcarbo/docker-caddy
    entrypoint: /bin/sh -c 'echo "$$BLA" | tee /etc/Caddyfile && echo "$$HELLO_WORLD" | tee /bla/index.html && /usr/bin/caddy -conf /etc/Caddyfile --log stdout'
    environment:
      BLA: |-
        bla.127.0.0.1.xip.io:80 {
          root /bla 
          basicauth /fm foo bar
          filemanager /fm {
            show /bla
          }
        }
      HELLO_WORLD: |-
        <html>
          <body>
            Hello world
          </body>
        </html>
    volumes:
      - $PWD:/bla
    ports:
      - "7777:80"
